version: '3.8'
services:
  maze_generator:
    build:
      context: .
      dockerfile: Dockerfile.maze_display
    volumes:
      - maze_data:/app/data

  a_star_solver:
    build:
      context: .
      dockerfile: Dockerfile.a_star_solver
    volumes:
      - maze_data:/app/data
    depends_on:
      - maze_generator

  maze_display:
    build:
      context: .
      dockerfile: Dockerfile.maze_display
    volumes:
      - maze_data:/app/data
    depends_on:
      - a_star_solver

volumes:
  maze_data:
